import {
  FiAlertTriangle,
  FiBarChart2,
  FiBell,
  FiBriefcase,
  FiCalendar,
  FiCamera,
  FiCheck,
  FiCheckCircle,
  FiClipboard,
  FiCompass,
  FiCornerUpLeft,
  FiEdit3,
  FiHeart,
  FiHome,
  FiImage,
  FiMap,
  FiMapPin,
  FiMaximize,
  FiMessageSquare,
  FiPhone,
  FiSearch,
  FiShield,
  FiTag,
  FiTrash2,
  FiTrendingUp,
  FiUser,
  FiUsers,
} from "react-icons/fi";
import { FaBed, FaBuilding, FaShower } from "react-icons/fa";

const ICONS = {
  alert: FiAlertTriangle,
  area: FiMaximize,
  bath: FaShower,
  bed: FaBed,
  bell: FiBell,
  briefcase: FiBriefcase,
  building: FaBuilding,
  calendar: FiCalendar,
  camera: FiCamera,
  check: FiCheck,
  success: FiCheckCircle,
  clipboard: FiClipboard,
  compass: FiCompass,
  edit: FiEdit3,
  heart: FiHeart,
  home: FiHome,
  image: FiImage,
  map: FiMap,
  location: FiMapPin,
  message: FiMessageSquare,
  phone: FiPhone,
  reply: FiCornerUpLeft,
  search: FiSearch,
  shield: FiShield,
  tag: FiTag,
  trash: FiTrash2,
  trend: FiTrendingUp,
  chart: FiBarChart2,
  user: FiUser,
  users: FiUsers,
};

export default function UiIcon({ name, size = 18, ...props }) {
  const Icon = ICONS[name] || FiHome;
  return <Icon size={size} aria-hidden="true" {...props} />;
}
